permalink: /:categories/:year/:month/:day/:title

exclude: ["ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

title : Surviving Mars
author :
  name : Ralitsa
  email : ralitza08@gmail.com
  github : cupcakemagic

production_url : https://cupcakemagic.github.io/new_site

JB :
  version : 0.3.0
  BASE_PATH : https://cupcakemagic.github.io/new_site

  archive_path: nil
  categories_path : nil
  tags_path : nil
  atom_path : nil
  rss_path : nil
  
  comments :
    provider : false

  analytics :
    provider : false

  sharing :
    provider : false
