permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

title : Surviving Mars Documentation
author :
  name : Ralitsa
  email : https://www.haemimontgames.com/
  github : haemimontgames
  twitter : haemimontgames
  feedburner : nil

production_url : https://cupcakemagic.github.io/trying_new_site/

markdown: kramdown

JB :
  version : 0.3.0

  BASE_PATH : https://cupcakemagic.github.io/trying_new_site/

  archive_path: nil
  categories_path : nil
  tags_path : nil
  atom_path : nil
  rss_path : nil

  comments :
    provider : false

  analytics :
    provider : false

  sharing :
    provider : false
